[font]
size = 15

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[scrolling]
history = 10000
